/*CREATE TABLE t1 (i INT, j INT);
CREATE TABLE t2 (k CHAR(1), j INT);
INSERT INTO t1 VALUES(1, 1);
INSERT INTO t1 VALUES(2,1);
INSERT INTO t1 VALUES(3,1);
INSERT INTO t1 VALUES(1,2);
INSERT INTO t1 VALUES(2,NULL);
INSERT INTO t1 VALUES(4,NULL);
INSERT INTO t1 VALUES(5,NULL);
INSERT INTO t2 VALUES("a", 1);
INSERT INTO t2 VALUES("b", 2);
INSERT INTO t2 VALUES("c", 3);
INSERT INTO t2 VALUES("d", NULL);
INSERT INTO t2 VALUES("e", NULL);
*/
SELECT * FROM t1 JOIN t2  ON t1.j = t2.j;
SELECT * FROM t1 LEFT JOIN t2 ON t1.j = t2.j;
SELECT * FROM t1 RIGHT JOIN t2 ON t1.j = t2.j;
-- SELECT * FROM t1 FULL JOIN t2 ON t1.j = t2.j;
SELECT * FROM t1 CROSS JOIN t2 ON t1.j = t2.j;
-- Simular um FULL JOIN NO MYSQL
SELECT * FROM t1
LEFT JOIN t2 ON  t1.j = t2.j
UNION
SELECT * FROM t1
RIGHT JOIN t2 ON  t1.j = t2.j;